/**
  * @file    mdbs_dev.h
  * @brief   MODBUS Device
  * @author  Igor T. <research.tahoe@gmail.com>
  */


#ifndef MDBS_DEV_H
#define MDBS_DEV_H


typedef enum    mdbs_hreg_e
{
        MDBS_HREG_DEVICE_ID_HI          = 0,
        MDBS_HREG_DEVICE_ID_LO,
        MDBS_HREG_HARDWARE_ID_HI,
        MDBS_HREG_HARDWARE_ID_LO,
        MDBS_HREG_FIRMWARE_ID_HI,
        MDBS_HREG_FIRMWARE_ID_MI,
        MDBS_HREG_FIRMWARE_ID_LO,
        MDBS_HREG_STARTS_COUNTER,
        MDBS_HREG_RESERVED_08,
        MDBS_HREG_RESERVED_09,
        MDBS_HREG_RESERVED_0A,
        MDBS_HREG_RESERVED_0B,
        MDBS_HREG_RESERVED_0C,
        MDBS_HREG_RESERVED_0D,
        MDBS_HREG_RESERVED_0E,
        MDBS_HREG_RESERVED_0F,

        MDBS_HREG_SERIAL_NUM_00,
        MDBS_HREG_SERIAL_NUM_01,
        MDBS_HREG_SERIAL_NUM_02,
        MDBS_HREG_SERIAL_NUM_03,
        MDBS_HREG_SERIAL_NUM_04,
        MDBS_HREG_SERIAL_NUM_05,
        MDBS_HREG_SERIAL_NUM_06,
        MDBS_HREG_SERIAL_NUM_07,
        MDBS_HREG_RESERVED_18,
        MDBS_HREG_RESERVED_19,
        MDBS_HREG_RESERVED_1A,
        MDBS_HREG_RESERVED_1B,
        MDBS_HREG_RESERVED_1C,
        MDBS_HREG_RESERVED_1D,
        MDBS_HREG_RESERVED_1E,
        MDBS_HREG_RESERVED_1F,


        MDBS_HREG_SENS_R0_PPM_HI,
        MDBS_HREG_SENS_R0_PPM_LO,
        MDBS_HREG_SENS_RAW,
        MDBS_HREG_SENS_INSTABILITY,
        MDBS_HREG_RESERVED_24,
        MDBS_HREG_RESERVED_25,
        MDBS_HREG_RESERVED_26,
        MDBS_HREG_RESERVED_27,

        MDBS_HREG_RESERVED_28,
        MDBS_HREG_RESERVED_29,
        MDBS_HREG_TEMP_BRD_CELS,
        MDBS_HREG_SENS_OFST_RAW,
        MDBS_HREG_MCU_TEMP_CELS,
        MDBS_HREG_MCU_VDDA_mV,
        MDBS_HREG_RESERVED_2E,
        MDBS_HREG_ERR_CODE_LAST,


        MDBS_HREG_TRIM_0_VALUE_HI,
        MDBS_HREG_TRIM_0_VALUE_LO,
        MDBS_HREG_TRIM_0_TIMESTAMP_HI,
        MDBS_HREG_TRIM_0_TIMESTAMP_LO,
        MDBS_HREG_TRIM_1_VALUE_HI,
        MDBS_HREG_TRIM_1_VALUE_LO,
        MDBS_HREG_TRIM_1_TIMESTAMP_HI,
        MDBS_HREG_TRIM_1_TIMESTAMP_LO,
        MDBS_HREG_RESERVED_38,
        MDBS_HREG_RESERVED_39,
        MDBS_HREG_RESERVED_3A,
        MDBS_HREG_RESERVED_3B,
        MDBS_HREG_RESERVED_3C,
        MDBS_HREG_RESERVED_3D,
        MDBS_HREG_RESERVED_3E,
        MDBS_HREG_RESERVED_3F,

        MDBS_HREG_MAX,
} mdbs_hreg_t;


#endif  //MDBS_DEV_H
